version: 2
updates:
- package-ecosystem: docker
  directory: "/2.10/alpine"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Etc/UTC
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/2.10/builder"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Etc/UTC
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/2.10/windows/ltsc2022"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Etc/UTC
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/2.10/windows/ltsc2025"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Etc/UTC
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/2.10/windows-builder/ltsc2022"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Etc/UTC
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/2.10/windows-builder/ltsc2025"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Etc/UTC
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/2.10/windows-nanoserver/ltsc2022"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Etc/UTC
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/2.10/windows-nanoserver/ltsc2025"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Etc/UTC
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/2.11/alpine"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Etc/UTC
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/2.11/builder"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Etc/UTC
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/2.11/windows/ltsc2022"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Etc/UTC
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/2.11/windows/ltsc2025"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Etc/UTC
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/2.11/windows-builder/ltsc2022"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Etc/UTC
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/2.11/windows-builder/ltsc2025"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Etc/UTC
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/2.11/windows-nanoserver/ltsc2022"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Etc/UTC
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/2.11/windows-nanoserver/ltsc2025"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Etc/UTC
  open-pull-requests-limit: 10
