name: Generate stackbrew library file
on:
  push:
    paths:
      - '*/Dockerfile'
      - stackbrew.tmpl
      - stackbrew-config.yaml

jobs:
  gen-stackbrew:
    runs-on: ubuntu-latest
    container:
      image: hairyhenderson/dockerfiles-builder:latest
    env:
      BASHBREW_LIBRARY: ./library
      BASHBREW_NAMESPACE: caddy
      DOCKER_BUILDKIT: '1'
    steps:
    - uses: actions/checkout@master
    - name: Reattach HEAD
      run: git checkout ${GITHUB_REF#refs/heads/}
    - run: make library/caddy
    - name: Configure git
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
    - name: Commit and push changes
      run: |
        git add library/caddy
        if output=$(git status --porcelain) && [ ! -z "$output" ]; then
          git commit -m 'chore: regenerate stackbrew library file'
          git push
        fi
